backend/controllers/ImportController.php
<?php

namespace backend\controllers;

use backend\services\NewImportHandlerService;
use backend\services\PriceList\NewService;
use backend\services\PriceList\StoreListService;
use common\exceptions\ValidationException;
use common\forms\ImportFileForm;
use common\models\Databases\ActiveRecords\Stores\Store;
use common\models\Databases\ActiveRecords\Stores\StoreProductImport;
use common\models\Databases\ActiveRecords\Stores\StoreProductImportState;
use common\models\Forms\Stores\Products\ImportUploadForm;
use common\repositories\ActiveRecords\Import\ImportCompletedLastRepository;
use common\repositories\ActiveRecords\Import\ImportFailedLastDaysRepository;
use common\repositories\ActiveRecords\Import\ImportNewLastRepository;
use common\repositories\ActiveRecords\Import\ImportProcessingRepository;
use common\repositories\ActiveRecords\Import\ImportRepository;
use common\services\StoreProductImportListing\FecthingAndOrderingRules\PrettyComfortableStrategy;
use common\services\StoreProductImportListing\StoreProductImportListingService;
use common\services\UploadedImportFileNameGeneratorService;
use Exception;
use Yii;
use yii\data\Pagination;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\UploadedFile;

/**
 * Class ImportController
 *
 * @package backend\controllers
 */
class ImportController extends Controller
{
    public function actionDashboard(): string
    {
        $service = new StoreProductImportListingService(
            new ImportProcessingRepository,
            new ImportFailedLastDaysRepository,
            new ImportCompletedLastRepository,
            new ImportNewLastRepository
        );

        return $this->render(
            'dashboard',
            [
                'import' => $service->setFecthingAndOrderingRules(new PrettyComfortableStrategy())->makeListing(30)
            ]
        );
    }

    public function actionListing(): string
    {
        $pages = new Pagination(['totalCount' => StoreProductImport::count(), 'pageSize' => 50]);

        return $this->render(
            'listing',
            [
                'import' => (new ImportRepository)->get($pages->limit, $pages->offset),
                'pages' => $pages,
            ]
        );
    }

    public function actionStore()
    {
        try {
            $model = new ImportUploadForm();
            $service = new NewImportHandlerService(
                $model,
                new UploadedImportFileNameGeneratorService,
                Yii::$app->params['queue.service.store.productImport.parallelHandlersPerCompany']
            );
            $service->getFileNameGeneratorService()->setStorageDirectoryBasePath(getenv('DIR_CDN') ?: '/cdn');
            if(Yii::$app->request->isPost) {
                $service->handle(Yii::$app->request);

                return $this->redirect('/import/dashboard');
            }
        } catch (ValidationException $exception) {
            // nothing
        }

        return $this->render(
            'forms/upload-import',
            ['widget' => new ImportFileForm(new \yii\widgets\ActiveForm, $model)]
        );
    }
}

backend/controllers/ProductController.php
<?php

namespace backend\controllers;

use common\models\Databases\ActiveRecords\Stores\Product;
use common\models\Databases\ActiveRecords\Stores\StoreProductImport;
use yii\data\Pagination;
use yii\web\Controller;

/**
 * Class ProductsController
 *
 * @package backend\controllers
 */
class ProductController extends Controller
{
    public function actionStorePriceList(int $storeId): string
    {
        $pages = new Pagination(['totalCount' => Product::count(), 'pageSize' => 50]);
        return $this->render(
            'price-list',
            [
                'products' => Product::findByStoreId($storeId, $pages->limit, $pages->offset),
                'pages' => $pages
            ]);
    }
}

backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use common\models\Forms\Auth\LoginForm;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\ErrorAction;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return ['error' => ['class' => ErrorAction::class,]];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $this->layout = 'blank';
        $model = new LoginForm;

        /** @noinspection NotOptimalIfConditionsInspection */
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';

        return $this->render('login', ['model' => $model,]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

backend/controllers/StoreController.php
<?php

namespace backend\controllers;

use backend\services\PriceList\StoreListService;
use yii\web\Controller;

/**
 * Class ProductsController
 *
 * @package backend\controllers
 */
class StoreController extends Controller
{
    public function actionList(): string
    {
        return $this->render('list', ['stores' => (new StoreListService)->execute()]);
    }
}

backend/views/import/dashboard.php
<?php
/**
 * @var array[] $import
 */

use yii\helpers\Url;

?>
<div class="site-index">

  <div class="jumbotron">
    <h1>Import dashboard!</h1>

    <p class="lead">The imported files from the queue, failed imporing and the last completed importing are
      displayed here.</p>

    <p>
      <a class="btn btn-lg btn-info" href="<?= Url::toRoute('/import/listing') ?>">Full list</a>
      <a class="btn btn-lg btn-success" href="<?= Url::toRoute('/import/add') ?>">Add import</a>
    </p>
  </div>
  <div class="body-content">
    <div class="row table-custom">
      <table>
        <thead>
        <tr>
          <td>Id</td>
          <td colspan="2">Store</td>
          <td colspan="2">File</td>
          <td>State</td>
          <td colspan="3">Products</td>
        </tr>
        <tr>
          <td>Id</td>
          <td>Id</td>
          <td>Name</td>
          <td>Server path</td>
          <td>Origin name</td>
          <td></td>
          <td>Imported products</td>
          <td>Fails</td>
          <td>Total</td>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($import as $row) { ?>
          <tr>
            <td><?= $row['id'] ?></td>
            <td><?= $row['store_id'] ?></td>
            <td><?= $row['store_name'] ?></td>
            <td><?= $row['file_path'] ?></td>
            <td><?= $row['file_name_origin'] ?></td>
            <td><?= $row['state_name'] ?></td>
            <td><?= $row['count_total'] == 0 ? '' : ($row['count_processing_done'] - $row['count_fail']) ?></td>
            <td><?= $row['count_total'] == 0 ? '' : $row['count_fail'] ?></td>
            <td><?= ($row['has_failed'] == true) ? 'Failed' : ($row['count_total'] == 0 ? 'Unknown' : $row['count_total']) ?></td>
          </tr>
        <?php } ?>
        </tbody>
      </table>
    </div>
  </div>
</div>

backend/views/import/forms/upload-import.php
<?php
/**
 * @noinspection PhpFullyQualifiedNameUsageInspection
 *
 * @var \yii\widgets\ActiveForm $form
 * @var \common\models\Forms\Stores\Products\ImportUploadForm $model
 * @var \common\forms\ImportFileForm $widget
 */

//echo $widget;

$widget->begin();
echo $widget->getPropertyFileName();
echo $widget->getPropertyStore();
echo $widget->getButtonSubmit();
$widget->end();

backend/views/import/listing.php
<?php
/**
 * @var array[] $import
 */

use yii\helpers\Url;

?>

<div class="site-index">

  <div class="jumbotron">
    <h1>Import!</h1>

    <p class="lead">The imported files from the queue, failed imporing and the last completed importing are
      displayed here.</p>

    <p><a class="btn btn-lg btn-success" href="<?= Url::toRoute('/import/add') ?>">Add import</a></p>
  </div>
  <div class="body-content">
    <div class="row"><?= \yii\widgets\LinkPager::widget(['pagination' => $pages]) ?></div>
    <div class="row table-custom">
      <table>
        <thead>
        <tr>
          <td>Id</td>
          <td colspan="2">Store</td>
          <td colspan="2">File</td>
          <td>State</td>
          <td colspan="3">Products</td>
        </tr>
        <tr>
          <td>Id</td>
          <td>Id</td>
          <td>Name</td>
          <td>Server path</td>
          <td>Origin name</td>
          <td></td>
          <td>Imported products</td>
          <td>Fails</td>
          <td>Total</td>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($import as $row) { ?>
          <tr>
            <td><?= $row['id'] ?></td>
            <td><?= $row['store_id'] ?></td>
            <td><?= $row['store_name'] ?></td>
            <td><?= $row['file_path'] ?></td>
            <td><?= $row['file_name_origin'] ?></td>
            <td><?= $row['state_name'] ?></td>
            <td><?= $row['count_total'] == 0 ? '' : ($row['count_processing_done'] - $row['count_fail']) ?></td>
            <td><?= $row['count_total'] == 0 ? '' : $row['count_fail'] ?></td>
            <td><?= ($row['has_failed'] == true) ? 'Failed' : ($row['count_total'] == 0 ? 'Unknown' : $row['count_total']) ?></td>
          </tr>
        <?php } ?>
        </tbody>
      </table>
    </div>
    <div class="row"><?= \yii\widgets\LinkPager::widget(['pagination' => $pages]) ?></div>
  </div>
</div>

backend/views/layouts/blank.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="blank">
<?php $this->beginBody() ?>

    <div class="wrap">
        <?= $content ?>
    </div>

</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);

    $menuItems = Yii::$app->params['menuItems'] ?? [];

    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/product/price-list.php
<?php
/** @noinspection PhpFullyQualifiedNameUsageInspection */

/** @var \common\models\Databases\ActiveRecords\Stores\Product[] $products */
?><h1>Prices:</h1>

<div class="row"><?= \yii\widgets\LinkPager::widget(['pagination' => $pages]) ?></div>
<div class="row table-custom">
<table>
  <thead>
  <tr>
    <td>#</td>
    <td>UPC</td>
    <td>Title</td>
    <td>Price</td>
  </tr>
  </thead>
  <tbody>
  <?php foreach ($products as $k => $product) { ?>
    <tr>
      <td><?= $k + 1 ?></td>
      <td><b><?= $product->upc ?></b></td>
      <td><?= $product->title ?></td>
      <td><b><?= $product->price ?></b></td>
    </tr>
  <?php } ?>
  </tbody>
</table>
</div>
<div class="row"><?= \yii\widgets\LinkPager::widget(['pagination' => $pages]) ?></div>

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

backend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary btn-block', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
</div>

backend/views/store/list.php
<?php
/**
 * @noinspection PhpFullyQualifiedNameUsageInspection
 *
 * @var \backend\dto\StoreForLinkWithPriceDto[]|\Generator $stores
 */

?><h1>Companies:</h1>
<ul>
    <?php foreach ($stores as $store) { ?>
      <li><?= \yii\helpers\Html::a(
              $store->getTitle() . '  ( ' . $store->getCountProducts() . ' )',
              \yii\helpers\Url::to(['product/store-price-list', 'storeId' => $store->getId()])
          ) ?></li>
    <?php } ?>
</ul>